SET(CPACK_GENERATOR "DEB")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Geoff Rosenberg")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")

install(TARGETS puzzle-demo
  DESTINATION "/usr/local/bin/")

INCLUDE(CPack)
