name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: sudo apt-get install ninja-build googletest valgrind
      run: sudo mkdir /usr/src/googletest/build
      run: sudo cd /usr/src/googletest/build
      run: sudo export CC=$(which clang) && sudo export CXX=$(which clang++)
      run: sudo cmake -G "Ninja" ..
      run: sudo ninja
      run: sudo ninja install
      run: sudo cd -

    - name: Run build script
      run: ./ci_build.sh
