name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prereqs
      run: sudo apt-get install ninja-build googletest valgrind

    - name: Install googletest
      run: sudo ./install_build_prereqs.sh

    - name: Run build script
      run: ./ci_build.sh
